home_page:
    path: /
    methods: GET
    controller: App\Controller\HomeController::greetAPIUsers

create_items:
    path: /api/items/create
    methods: POST
    controller: App\Controller\ItemController::createItems

get_items:
    path: /api/items
    methods: GET
    controller: App\Controller\ItemController::getItems

create_order:
    path: /api/order/create
    methods: POST
    controller: App\Controller\OrderController::createOrder

pay_order:
    path: /api/order/pay
    methods: POST
    controller: App\Controller\OrderController::payOrder

