home_page:
    path: /
    methods: GET
    controller: App\Controller\HomeController::greetAPIUsers

create_items:
    path: /api/create-items
    methods: POST
    controller: App\Controller\ItemController::createItems

get_items:
    path: /api/get-items
    methods: GET
    controller: App\Controller\ItemController::getItems

create_order:
    path: /api/create-order
    methods: POST
    controller: App\Controller\OrderController::createOrder
