imports:
    - { resource: parameters/db.yaml }

parameters:
    order.pay_check_url: 'http://ya.ru'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        App\Core\BaseRepository:
            calls:
                - ['setDBConnection', ['@app.db_connection']]

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Events}'

    App\Controller\:
        public: true
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Core\DBConnection:
        arguments: ['%db%']

    app.db_connection:
        alias: 'App\Core\DBConnection'
        public: true

    App\Service\ItemGeneratorServiceInterface: '@App\Service\ItemGeneratorService'

    App\Service\CreateOrderServiceInterface: '@App\Service\CreateOrderService'

    App\Service\OrderPayService:
        arguments:
            $payCheckURL: '%order.pay_check_url%'

    App\Service\OrderPayServiceInterface: '@App\Service\OrderPayService'

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client
