services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Core,Migrations,Events}'

    App\Controller\:
        public: true
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
